packages:
  - apps/builder-cjs
  - apps/builder-esm
  - apps/forge-cjs
  - apps/forge-esm
  - apps/no-binary-cjs
  - apps/no-binary-esm
  - e2e
  - packages/@wdio_electron-bundler
  - packages/@wdio_electron-types
  - packages/@wdio_electron-utils
  - packages/wdio-electron-service
catalog:
  "@electron-forge/cli": ^7.7.0
  "@electron-forge/shared-types": ^7.7.0
  "@electron/packager": ^18.3.6
  "@eslint/js": ^9.22.0
  "@inquirer/prompts": ^7.4.0
  "@octokit/rest": ^21.1.1
  "@octokit/types": ^13.10.0
  "@rollup/plugin-commonjs": ^28.0.3
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-typescript": ^12.1.2
  "@turbo-version/version": ^0.8.3
  "@types/debug": ^4.1.12
  "@types/eslint-config-prettier": ^6.11.3
  "@types/mocha": ^10.0.10
  "@types/node": ^22.13.10
  "@types/shelljs": ^0.8.15
  "@typescript-eslint/eslint-plugin": ^8.27.0
  "@typescript-eslint/parser": ^8.27.0
  "@vitest/coverage-v8": ^3.0.9
  "@vitest/eslint-plugin": ^1.1.38
  "@vitest/spy": ^3.0.9
  "@wdio/cli": ^9.12.1
  "@wdio/globals": ^9.12.1
  "@wdio/local-runner": ^9.12.1
  "@wdio/logger": ^9.4.4
  "@wdio/mocha-framework": ^9.12.1
  "@wdio/types": ^9.10.1
  builder-util: ^25.1.7
  chalk: ^5.4.1
  compare-versions: ^6.1.1
  cross-env: ^7.0.3
  debug: ^4.4.0
  dotenv: ^16.4.7
  electron: ^35.0.2
  electron-builder: ^25.1.8
  electron-to-chromium: ^1.5.122
  eslint: ^9.22.0
  eslint-config-prettier: ^10.1.1
  eslint-import-resolver-typescript: ^4.2.2
  eslint-plugin-import-x: ^4.9.1
  eslint-plugin-wdio: ^9.9.1
  fast-copy: ^3.0.2
  find-versions: ^6.0.0
  globals: ^16.0.0
  husky: ^9.1.7
  jsdom: ^26.0.0
  json5: ^2.2.3
  lint-staged: ^15.5.0
  list: ^2.0.19
  nock: ^14.0.1
  ora: ^8.2.0
  prettier: ^3.5.3
  puppeteer-core: ^22.15.0
  read-package-up: ^11.0.0
  rollup: ^4.36.0
  rollup-plugin-node-externals: ^8.0.0
  shelljs: ^0.9.2
  shx: ^0.4.0
  smol-toml: ^1.3.1
  tinyspy: ^4.0.0
  tsx: ^4.19.3
  turbo: ^2.4.4
  typescript: ^5.8.2
  vitest: ^3.0.9
  webdriverio: ^9.12.1
  xvfb-maybe: ^0.2.1
  yaml: ^2.7.0
