packages:
  - 'apps/builder-cjs'
  - 'apps/builder-esm'
  - 'apps/forge-cjs'
  - 'apps/forge-esm'
  - 'apps/no-binary-cjs'
  - 'apps/no-binary-esm'
  - 'e2e'
  - 'packages/@wdio_electron-bundler'
  - 'packages/@wdio_electron-types'
  - 'packages/@wdio_electron-utils'
  - 'packages/wdio-electron-service'
