packages:
  - 'apps/builder-cjs'
  - 'apps/builder-esm'
  - 'apps/forge-cjs'
  - 'apps/forge-esm'
  - 'apps/no-binary-cjs'
  - 'apps/no-binary-esm'
  - 'e2e'
  - 'packages/@wdio_electron-bundler'
  - 'packages/@wdio_electron-cdp-bridge'
  - 'packages/@wdio_electron-types'
  - 'packages/@wdio_electron-utils'
  - 'packages/wdio-electron-service'

catalogs:
  default:
    electron: ^36.6.0
    webdriverio: ^9.15.0
    '@wdio/cli': ^9.15.0
    '@wdio/globals': ^9.15.0
    '@wdio/local-runner': ^9.15.0
    '@wdio/mocha-framework': ^9.15.0
  next:
    electron-nightly: 38.0.0-nightly.20250624
    webdriverio: latest
    '@wdio/cli': latest
    '@wdio/globals': latest
    '@wdio/local-runner': latest
    '@wdio/mocha-framework': latest
  minimum:
    electron: ^28.0.0
    webdriverio: ^8.43.0
    '@wdio/cli': ^8.43.0
    '@wdio/globals': ^8.43.0
    '@wdio/local-runner': ^8.43.0
    '@wdio/mocha-framework': ^8.41.0
