packages:
  - 'fixtures/e2e-apps/builder-cjs'
  - 'fixtures/e2e-apps/builder-esm'
  - 'fixtures/e2e-apps/forge-cjs'
  - 'fixtures/e2e-apps/forge-esm'
  - 'fixtures/e2e-apps/no-binary-cjs'
  - 'fixtures/e2e-apps/no-binary-esm'
  - 'e2e'
  - 'packages/@wdio_electron-bundler'
  - 'packages/@wdio_electron-cdp-bridge'
  - 'packages/@wdio_electron-types'
  - 'packages/@wdio_electron-utils'
  - 'packages/wdio-electron-service'

catalogs:
  default:
    electron: ^37.1.0
    webdriverio: ^9.16.2
    '@wdio/cli': ^9.16.2
    '@wdio/globals': ^9.16.2
    '@wdio/local-runner': ^9.16.2
    '@wdio/mocha-framework': ^9.16.2
    '@wdio/types': ^9.16.2
    '@wdio/logger': ^9.16.2
  next:
    electron-nightly: 39.0.0-nightly.20250625
    webdriverio: latest
    '@wdio/cli': latest
    '@wdio/globals': latest
    '@wdio/local-runner': latest
    '@wdio/mocha-framework': latest
    '@wdio/types': latest
    '@wdio/logger': latest
  minimum:
    electron: ^28.0.0
    webdriverio: ^8.43.0
    '@wdio/cli': ^8.43.0
    '@wdio/globals': ^8.43.0
    '@wdio/local-runner': ^8.43.0
    '@wdio/mocha-framework': ^8.41.0
    '@wdio/types': ^8.41.0
    '@wdio/logger': ^8.41.0
