name: Lint
description: 'Runs code quality checks across the codebase'

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  lint:
    name: Code Quality Checks
    strategy:
      fail-fast: false
      matrix:
        node-version: ['20']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: 👷 Checkout Repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: 🛠️ Setup Development Environment
        uses: ./.github/workflows/actions/setup-workspace
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Download Build Artifacts
        uses: ./.github/workflows/actions/download-archive
        with:
          name: wdio-electron-service
          path: .
          filename: wdio-electron-service-build.zip

      - name: 🔍 Run Code Quality Checks
        run: pnpm run lint
        shell: bash
